_base_: '../_base_/panel.yml'

batch_size: 16
iters: 200

model:
  type: SFNet
  backbone:
    type: ResNet18_vd
    output_stride: 8
    pretrained: /content/drive/MyDrive/panel_detection/pretrained_sfnet.pdparams
  backbone_indices: [0, 1, 2, 3]


loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005
